version: '3.8'
services:
  db:
    image: postgres:14.3-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
    user: postgres
    container_name: foodgram_db_psql
  backend:
    image: a8158d7bb42c/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/backend/backend_static/
      - media_value:/backend/backend_media/
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    image: a8158d7bb42c/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
      - ../frontend/:/app/result_build/
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - frontend
      - backend
      - db
volumes:
  static_value:
  media_value:
  db_value:


